export const HOME = '/'
export const HOOKS = '/hooks'
export const HOOK = '/hooks/:ipfsHash'
export const CONFIRM = '/dapp-users/confirm'
export const DAPP_SIGNUP = '/dapp-signup'
export const DAPP_CONFIRM = '/dapp-confirm/:dapp_name/:api_key'
export const API_DOCS = '/api-docs'
